[build]
# Build the agent service
buildCommand = "cd agent && docker build -t cartesia-voice-agent ."
watchPatterns = ["agent/**"]

[deploy]
# Health check configuration
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Environment variables documentation
# These must be set in the Railway dashboard:
# LIVEKIT_URL - Your LiveKit WebSocket URL
# LIVEKIT_API_KEY - Your LiveKit API key
# LIVEKIT_API_SECRET - Your LiveKit API secret
# CARTESIA_API_KEY - Your Cartesia API key for TTS
# OPENAI_API_KEY - Your OpenAI API key for LLM
# DEEPGRAM_API_KEY - Your Deepgram API key for STT

[experimental]
# Enable experimental features if needed
incremental = true